dist: xenial
language: python
python:
  - 3.7
cache: pypi

install:
  - pip install flake8 codecov pytest pytest-cov
  - pip install -r requirements.txt

script:
  - python -m --ignore E501 flake8 international_trade_models/
  - python -m pytest -vvv international_trade_models/tests/ricardian_tests.py --cov international_trade_models

after_success:
  - codecov
 
branches:
  only:
  - main
